export const projects: Project[] = [
  {
    title: 'Proyecto 1',
    id: '1',
    banner_card: 'https://picsum.photos/400/500',
    logo: 'https://picsum.photos/500/200',
    currency: 'USD',
    location: 'ASIA',
    km: 'Panam. Sur Km. 152.5',

    initial: 10,
    price: 100,
    min_area: '100',
  },
  {
    title: 'Proyecto 1',
    id: '2',
    banner_card: 'https://picsum.photos/400/500',
    logo: 'https://picsum.photos/500/200',
    currency: 'USD',
    location: 'ASIA',
    km: 'Panam. Sur Km. 152.5',

    initial: 10,
    price: 100,
    min_area: '100',
  },
  {
    title: 'Proyecto 1',
    id: '3',
    banner_card: 'https://picsum.photos/400/500',
    logo: 'https://picsum.photos/500/200',
    currency: 'USD',
    location: 'ASIA',
    km: 'Panam. Sur Km. 152.5',

    initial: 10,
    price: 100,
    min_area: '100',
  },
  {
    title: 'Proyecto 1',
    id: '4',
    banner_card: 'https://picsum.photos/400/500',
    logo: 'https://picsum.photos/500/200',
    currency: 'USD',
    location: 'ASIA',
    km: 'Panam. Sur Km. 152.5',
    initial: 10,
    price: 100,
    min_area: '100',
  },
];
